spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unisec
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true