spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_message
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true