management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: ${CONFIG_SERVER_PORT:8011}

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_IP:localhost}:${REGISTRY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: config-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

logging.file.name: ../logs/config-service.log
