server:
  port: ${I18SERVICE_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_IP:localhost}:${REGISTRY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: security-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

logging.file.name: ../logs/security-service.log

spring:
  flyway:
    baseline-on-migrate: true
    table: schema_version  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
      
