server:
  port: ${I18SERVICE_PORT:0}

logging.file.name: logs/i18-service.log

spring:
  flyway:
    baseline-on-migrate: true
    table: schema_version
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS